=pod

=head1 TODO

Fix all the FIXMEs and TODOs.

 $ grep -rn --exclude=TODO.pod -e TODO -e FIXME *

Trigger an ItemShipped (#6) when a regular check in is done on an ILL loan in Koha.

How do we get users from the detail page to the NNCIPP page/form in the OPAC?

=head1 DONE

Remove dead/unused code from Base.pm. DONE

Place a hold at the Owner Library when a RequestItem is received. DONE
 
Place a hold at the Home Library when sending ItemReceived. DONE

=cut
